-- DATABASE CREATION

CREATE DATABASE BANKING_APP;
USE BANKING_APP;


-- TABLE CREATION
-- TABLE USERS

CREATE TABLE USERS(
ID INT AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(50) UNIQUE,
PASSWORD VARCHAR(50),
BALANCE DOUBLE DEFAULT 0
);


-- TABLE TRANSACTIONS

CREATE TABLE TRANSACTIONS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(50),
	DESCRIPTION VARCHAR(255),
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- 	VALUES INSERTION

INSERT INTO USERS (USERNAME,PASSWORD,BALANCE)
VALUES('admin','admin123',0);


